### ISSUE TITLE
TabBar

### ISSUE THREAD

**Issue by m0m0i** [m0m0i/google-next-imagen-demo#3]
Expected to have three tab icons.
Take 'currentTab' state and setState function from the Top Container.
Change the currentTab state as a user taps the icons.
Generate, Image Edit, Copy Writing?

**Comment by hmdsg** [comment]
https://github.com/m0m0i/google-next-imagen-demo/pull/8

**Comment by m0m0i** [comment]
close with https://github.com/m0m0i/google-next-imagen-demo/pull/8
